descriptor-schema-version: "2.5"

info:
  name: IOxGPS
  description: "GPS service"
  version: "1.0.0"
  author-link: "http://www.cisco.com"
  author-name: "Cisco Systems"

service-bundle:
   provides: [{id: "urn:cisco:system:service:protocolHandler:gps", api-version: 1,version: "1.0.0"}]

app:
  # Indicate app type (vm, paas, lxc etc.,)
  cpuarch: "x86_64"
  type: docker

  depends-on:
    packages:
      -
        name: "IOxCore"
        version: "1.7.0"

  resources:
    profile: c1.tiny
    network:
     -
       interface-name: eth0

  # Specify runtime and startup
  startup:
    rootfs: rootfs.tar
    target: ["/usr/share/gpsserviceapp/startup.sh start"]
